name: Build and Release frpclib AAR

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build AAR and Sources JAR, Upload to Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v2
        with:
          ndk: '27.0.12077973'

      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go get -u golang.org/x/mobile/bind
          gomobile init

      - name: Build AAR
        run: |
          mkdir -p build/output
          gomobile bind -v -target=android -androidapi 21 -o build/output/frpclib.aar github.com/fatedier/frp/cmd/frpc/frpclib

      - name: Create Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/output/frpclib.aar
            build/output/frpclib-sources.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
